// <auto-generated />
using AnimalShelterAPI.Solution.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterAPI.Solution.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200201004210_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterAPI.Solution.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Description");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Description = "Freindly cat that loves getting pet",
                            Gender = "Female",
                            Name = "Matilda",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 10,
                            Description = "A cat with a personaility, and she will let you know how she is feeling",
                            Gender = "Female",
                            Name = "Rexie",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Description = "Friendly dog that lives to cuddle and hang out with people",
                            Gender = "Female",
                            Name = "Matilda",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 4,
                            Description = "A ball of energy who loves to play anytime possible",
                            Gender = "Male",
                            Name = "Pip",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 12,
                            Description = "Was found on the streets, shy at first but once he warms up with you he'll never leave your side",
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
